name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Fly.io registry
        run: echo ${{ secrets.FLY_REGISTRY_TOKEN }} | docker login registry.fly.io -u x --password-stdin

      - name: Build Docker image
        run: docker build -t flyluke:latest .

      - name: Tag Docker image
        run: docker tag flyluke:latest registry.fly.io/nexentra-db

      - name: Push Docker image
        run: docker push registry.fly.io/nexentra-db

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --image registry.fly.io/nexentra-db --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
